-- V1__Create_Initial_Schema.sql
-- RESPONSABILIDADE ÚNICA: Criar a estrutura de tabelas do zero.
-- Este script roda apenas uma vez na vida do banco de dados.

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(30) NOT NULL UNIQUE,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       name VARCHAR(255) NOT NULL,
                       cpf VARCHAR(11) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       level INT NOT NULL DEFAULT 1,
                       xp BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role VARCHAR(255) NOT NULL,
                            PRIMARY KEY (user_id, role),
                            CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL UNIQUE,
                          description TEXT,
                          original_price NUMERIC(19, 2) NOT NULL,
                          discount_price NUMERIC(19, 2),
                          on_sale BOOLEAN NOT NULL DEFAULT FALSE,
                          xp BIGINT NOT NULL,
                          image_url VARCHAR(255) NOT NULL,
                          stock_quantity INT NOT NULL
);

CREATE TABLE product_tags (
                              product_id BIGINT NOT NULL,
                              tag VARCHAR(255) NOT NULL,
                              PRIMARY KEY (product_id, tag),
                              CONSTRAINT fk_product_tags_product_id FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);